// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    id: "1",
    amount: "per 1 Apple",
    caloriesPerAmount: 40,
    date: "Wed Dec 02 2020",
    foodName: "apple",
    mealTime: "Breakfast",
    portion: 1.2,
    carbsAmount: 13,
    fatAmount: 0,
    proteinAmount: 0,
  },
  {
    id: "2",
    amount: "per 1 Banana",
    caloriesPerAmount: 88,
    date: "Wed Dec 12 2020",
    foodName: "banana",
    mealTime: "Lunch",
    portion: 0.9,
    carbsAmount: 18,
    fatAmount: 0,
    proteinAmount: 0,
  },
  {
    id: "3",
    amount: "1 portion",
    caloriesPerAmount: 900,
    date: "Wed Dec 10 2020 00:00:00 GMT-0500",
    foodName: "Pad Thai",
    mealTime: "Dinner",
    portion: 0.8,
    carbsAmount: 130,
    fatAmount: 25,
    proteinAmount: 12,
  },
  {
    id: "4",
    amount: "per 1 Hot dog",
    caloriesPerAmount: 335,
    date: "Wed Dec 10 2020 00:00:00 GMT-0500",
    foodName: "Hot dog",
    mealTime: "Snack",
    portion: 1,
    carbsAmount: 130,
    fatAmount: 18,
    proteinAmount: 21,
  },
];
